# frozen_string_literal: true

# =============================================================================
# rake legal:build
#
# Compile les fichiers Markdown de config/legal/ en partials HAML
# dans app/views/legal/generated/.
#
# Usage :
#   bundle exec rails legal:build
#
# Le pipeline de déploiement (bin/deploy) appelle cette tâche automatiquement.
# Relancez-la manuellement après toute modification des fichiers .md.
# =============================================================================

namespace :legal do
  desc "Compile les fichiers Markdown de config/legal/ en partials HAML"
  task build: :environment do
    require 'redcarpet'

    source_dir = Rails.root.join("config", "legal")
    dest_dir   = Rails.root.join("app", "views", "legal", "generated")
    FileUtils.mkdir_p(dest_dir)

    renderer = Redcarpet::Render::HTML.new(
      hard_wrap:       false,
      safe_links_only: true,
      with_toc_data:   true,
    )
    markdown = Redcarpet::Markdown.new(
      renderer,
      autolink:            true,
      tables:              true,
      fenced_code_blocks:  true,
      strikethrough:       true,
      no_intra_emphasis:   true,
      superscript:         false,
    )

    md_files = Dir.glob(source_dir.join("*.fr.md"))
    if md_files.empty?
      puts "  Aucun fichier .fr.md trouvé dans #{source_dir}"
      next
    end

    md_files.each do |md_file|
      # cgu.fr.md → _cgu.html.haml
      basename  = File.basename(md_file, ".fr.md")
      dest_file = dest_dir.join("_#{basename}.html.haml")

      content_md   = File.read(md_file, encoding: "UTF-8")
      content_html = markdown.render(content_md)

      # Wrapper HAML minimal — le HTML généré est injecté via html_safe
      haml_content = <<~HAML
        -# Generated by rake legal:build — DO NOT EDIT DIRECTLY
        -# Source : config/legal/#{File.basename(md_file)}
        .legal-content
          = raw(<<~'HTML')
        #{content_html.gsub(/^/, '    ')}
          HTML
      HAML

      File.write(dest_file, haml_content, encoding: "UTF-8")
      puts "  ✔  #{File.basename(md_file)} → #{dest_file.relative_path_from(Rails.root)}"
    end

    puts "legal:build terminé — #{md_files.size} fichier(s) compilé(s)."
  end
end
